# Generated by Django 5.1.4 on 2024-12-18 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('category', models.CharField(choices=[('fashion', 'fashion'), ('household', 'household'), ('mobile', 'mobile'), ('laptop', 'laptop'), ('watches', 'watches')], max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('pic', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('MH', 'MH'), ('UP', 'UP'), ('MP', 'MP'), ('J&K', 'J&K')], max_length=10)),
                ('mobile', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harsh.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harsh.product')),
            ],
        ),
    ]
